package:
  name: vesper
  version: "0.1.2"

source:
  git_url: https://github.com/HaroldMills/Vesper.git
  git_rev: ignore-me

build:

  entry_points:
    - vcl=vesper.vcl.vcl:main
    - vesper_viewer=vesper.ui.vesper_viewer:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:

  build:
    - python
    - setuptools
    - matplotlib
    - pandas
    - pyephem
    - pyyaml
    - scikit-learn

  run:
    - python
    - matplotlib
    - pandas
    - pyephem
    - pyyaml
    - scikit-learn

test:

  imports:
    - vesper
 
  commands:
    - vcl help

about:
  home: https://github.com/HaroldMills/Vesper
  license: MIT
  license_file: LICENSE
  summary: 'Software for acoustical monitoring of nocturnal bird migration.'
