package:
  name: vesper
  version: "0.4.3"

source:
  # path: ..
  git_url: https://github.com/HaroldMills/Vesper.git
  git_rev: conda-build

build:

  entry_points:
    - vesper_admin=vesper.django.manage:main
    - vesper_recorder=vesper.scripts.vesper_recorder:_main
    - vesper_play_recorder_test_signal=vesper.scripts.play_recorder_test_signal:_main
    - vesper_show_audio_input_devices=vesper.scripts.show_audio_input_devices:_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:

  # Be careful about the packages included as dependencies in the
  # lists below. Including redundant packages (redundant because
  # they are dependencies of packages that are already included)
  # can cause build failures.
  #
  # Note, however, that it appears to be necessary to include the
  # Python package in both the build and run dependency lists,
  # even though it would seem to be redundant.
  
  build:
    - django 1.11*
    - jsonschema
    - keras
    - pyephem
    - python
    - resampy
    - scikit-learn
    - setuptools
 
  run:
    - django 1.11*
    - jsonschema
    - keras
    - pyephem
    - python
    - resampy
    - scikit-learn
 
test:

  imports:
    - vesper
 
  # commands:
  #   - vcl help

about:
  home: https://github.com/HaroldMills/Vesper
  license: MIT
  license_file: LICENSE
  summary: 'Software for acoustical monitoring of nocturnal bird migration.'
