package:
  name: vesper
  version: "0.0.1"

source:
  git_rev: ignore-me
  git_url: https://github.com/HaroldMills/Vesper.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - harold_test = harold_test:main
    #
    # Would create an entry point called harold_test that calls harold_test.main()

    - vcl=vesper.vcl.vcl:main
    - vesper_viewer=vesper.ui.vesper_viewer:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - matplotlib
    - pandas
    - pyephem
    - pyyaml
    - scikit-learn

test:
  # Python imports
  imports:
    - vesper
 
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - vcl help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/HaroldMills/Vesper
  license: MIT
  license_file: LICENSE
  summary: 'Software for acoustical nocturnal bird migration monitoring.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
