package:
  name: vesper
  version: "0.3.4"

source:
  git_url: https://github.com/HaroldMills/Vesper.git
  git_rev: conda-build

build:

  entry_points:
    - vesper_admin=vesper.django.manage:main
    - vesper_recorder=vesper.scripts.vesper_recorder:_main
    - vesper_play_recorder_test_signal=vesper.scripts.play_recorder_test_signal:_main
    - vesper_show_audio_input_devices=vesper.scripts.show_audio_input_devices:_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:

  build:
    - django 1.11*
    - jsonschema
    - numpy
    - pyephem
    - python
    - pytz
    - pyyaml
    - scikit-learn
    - setuptools

  run:
    - django 1.11*
    - jsonschema
    - numpy
    - pyephem
    - python
    - pytz
    - pyyaml
    - scikit-learn

test:

  imports:
    - vesper
 
  # commands:
  #   - vcl help

about:
  home: https://github.com/HaroldMills/Vesper
  license: MIT
  license_file: LICENSE
  summary: 'Software for acoustical monitoring of nocturnal bird migration.'
