package:
  name: vesper
  version: "0.2.2"

source:
  git_url: https://github.com/HaroldMills/Vesper.git
  git_rev: conda-build

build:

  entry_points:
    - vesper_admin=vesper.django.manage:main
    - vesper_record=vesper.scripts.record:_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:

  build:
    - bokeh
    - django
    - pyephem
    - python
    - pytz
    - pyyaml
    - setuptools

  run:
    - bokeh
    - django
    - pyephem
    - python
    - pytz
    - pyyaml

test:

  imports:
    - vesper
 
  # commands:
  #   - vcl help

about:
  home: https://github.com/HaroldMills/Vesper
  license: MIT
  license_file: LICENSE
  summary: 'Software for acoustical monitoring of nocturnal bird migration.'
